mybatis:
  config-location: classpath:com/example/demo/mybatis-config.xml
  
server:
  address: 0.0.0.0
  port: 9090
  
spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:file:~/Develop/kakao/demo_db;AUTO_SERVER=TRUE  #접속 URL
    username: demo  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)
  
  devtools:
    livereload:
      enabled: true
  
  